### ISSUE TITLE
Content refactor

### ISSUE THREAD

**Issue by adambutler** [rusic/documentation#15]
Content that could be improved -

- [x] Promote the object and variable reference
- [x] Find out all the available Liquid attributes in [Getting started](http://docs.rusic.com/getting-started/) does not link anywhere.
- [x] Add links to liquid docs

**Comment by nicholedwight** [comment]
@adambutler 
Object and variable reference have been bumped up into the getting started, just after the empty link to all Liquid attributes. https://github.com/rusic/documentation/pull/19 I had a looksie around to try to find a list of all the Liquid attributes available but that was a bit of a dead end, a lot of them pertained to a particular product/site. 
Also, which Liquid docs do we want to link to?

**Comment by adambutler** [comment]
Fixed by #20
